# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out code from the repository
    - name: check out code 
    - uses: actions/checkout@v4
      # Step 2: Set up python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' 
      # Step 3: Set up dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # Step 4: run unit test
    - name: Test with pytest
      run: |
        pytest
